lsnn_core_homepage:
    pattern:  /
    defaults: { _controller: LsnnCoreBundle:Creative:index }

creative_create:
    pattern:  /add-yourself
    defaults: { _controller: LsnnCoreBundle:Default:new }

about:
    pattern:  /about
    defaults: { _controller: LsnnCoreBundle:Default:about }
