parameters:
#    lsnn_core.example.class: Lsnn\CoreBundle\Example

services:
#    lsnn_core.example:
#        class: %lsnn_core.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
